### ISSUE TITLE
Use jwt gem instead of json-jwt

### ISSUE THREAD

**Issue by dzunk** [nhosoya/omniauth-apple#10]
The [`jwt`](http://rubygems.org/gems/jwt) gem is a more popular implementation than the [`json-jwt`](http://rubygems.org/gems/json-jwt) gem currently in use.  It's also a [required dependency](https://github.com/oauth-xx/oauth2/blob/master/oauth2.gemspec#L9) of `oauth2` through `omniauth-oauth2`, so it will already be present in the bundle. By switching to the `jwt` gem, we can avoid an additional dependency that duplicates existing functionality.

**Comment by fjaeger** [comment]
@nhosoya Do you mind merging the PR and releasing a new version of the gem? I also don't mind taking ownership of this repository and maintain it.

**Comment by bpleslie** [comment]
@nhosoya I'm also willing to help maintain this repo 😄

**Comment by dzunk** [comment]
Ditto 😃

**Comment by dzunk** [comment]
Fixed by #7
