### ISSUE TITLE
OmniAuth infoHash returns email as nil

### ISSUE THREAD

**Issue by elioncho** [nhosoya/omniauth-apple#12]
Hello,

I am experiencing a curious bug where the OmniAuth info hash returns email as nil for every Apple user that owns an iPhone that uses Face ID for authentication (iPhone X and above):
```
info=#<OmniAuth::AuthHash::InfoHash email=nil first_name=nil last_name=nil sub="001474.c261...."> provider="apple" uid="001474.c261..."
```

When I try the sign in, using Touch ID for authentication (iPhone 6s), it returns my valid email address in it, as it should be:
```
info=#<OmniAuth::AuthHash::InfoHash email="elioncho@gmail.com" first_name=nil last_name=nil sub="001273.a95..."> provider="apple" uid="001273.a95ed...">
```

Why is it that it returns nil when Face ID is used?

I attach some screenshots below of the flow I'm taking about:

![](https://i.stack.imgur.com/8sVJKl.jpg)
![](https://i.stack.imgur.com/aoCOjl.jpg)
![](https://i.stack.imgur.com/qaK2Jl.jpg)
![](https://i.stack.imgur.com/IHfmRl.jpg)

Thanks!

**Comment by sebfie** [comment]
Same here

**Comment by elioncho** [comment]
I think the issue is related to the way multiple scope attributes are encoded in the URL. I changed the default scope to just "email" and it worked correctly. When you try this, be sure to go into settings -> Touch your profile on the top -> Password and security -> Apple ID logins -> Touch your app -> Stop using Apple ID.

**Comment by sebfie** [comment]
It cames from faraday which transform space on GET url to "+", I fixed it using in an initializer : 

```ruby
OmniAuth::Strategies::OAuth2.class_eval do
  def request_phase
    redirect client.auth_code.authorize_url({:redirect_uri => callback_url}.merge(authorize_params)).gsub(/\+/, '%20')
  end
end
```

To have `%20` instead of `+` in url

**Comment by waissbluth** [comment]
@elioncho did you figure this out? I am still facing an issue very similar to yours (everything works well in our integration, except when a new user attempts a sign up using touch or face id). It does not make a difference if the callback is encoded with `+` or `%20`, the email is always missing in the response.

**Comment by elioncho** [comment]
> @elioncho did you figure this out? I am still facing an issue very similar to yours (everything works well in our integration, except when a new user attempts a sign up using touch or face id). It does not make a difference if the callback is encoded with `+` or `%20`, the email is always missing in the response.

Did you try only sending one attribute in the scope? See my previous comment. This is the conf. that worked for me:

```
 config.omniauth :apple, ENV['APPLE_CLIENT_ID'], '',
  {
    scope: 'email',
    team_id: Rails.application.credentials.apple_team_id,
    key_id: Rails.application.credentials.apple_key_id,
    pem: Base64.decode64(Rails.application.credentials.apple_private_key)
  }
```

**Comment by nov** [comment]
hope this merged, or do the same in your app.
https://gitlab.com/oauth-xx/oauth2/-/merge_requests/633
