### ISSUE TITLE
Can someone help explain refresh tokens to me?

### ISSUE THREAD

**Issue by eliduke** [nhosoya/omniauth-apple#21]
I was reading through [the Apple documentation on Verifying a User](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user) and it specifically talks about refresh tokens being used "to obtain access tokens with future calls."

I know that I am receiving a `refresh_token` in the response I get from Apple after authenticating, but I'm not seeing any reference to refresh tokens in this library. Am I missing something? Does this omniauth strategy automatically use refresh tokens? How do I implement it? Do I need to use a different library for that?

I am fairly new to omniauth / Apple SSO, so any and all help is much appreciated.

Thanks!

**Comment by nov** [comment]
you can get it via `request.env.dig('omniauth.auth', :credentials, :refresh_token)`.
it's set in `omniauth-oauth2` layer.
https://github.com/omniauth/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L50-L56

this gem doesn't use refresh_token at all, so if you need to use it, do it by yourself.
there is another gem to use it for token revocation etc.
https://github.com/nov/apple_id
