### ISSUE TITLE
What is CLIENT_ID and KEY_ID in config?

### ISSUE THREAD

**Issue by tampik** [nhosoya/omniauth-apple#22]
Where can I get client_id and key_id ?
There is not much information about client_id https://help.apple.com/developer-account/?lang=en#/dev1c0e25352

**Comment by drampelt** [comment]
I found it pretty confusing as well but eventually figured it out. 

First, setup Sign in with Apple for your app identifier at https://developer.apple.com/account/resources/identifiers/list. If you only need to sign in from your app, your app identifier will be the `client_id`. If you also need to be able to sign in on the web then you'll need to create a new Services ID for your website at https://developer.apple.com/account/resources/identifiers/add/bundleId, then that identifier will be your `client_id`.

Then you need to create a key at https://developer.apple.com/account/resources/authkeys/list with Sign in with Apple enabled and linked to your app. Once you create it you'll have a private key file and a key id that you can use with this gem.

**Comment by skotchpine** [comment]
omfg this is always rediculous, so I wrote a walkthrough: #62

**Comment by nov** [comment]
https://github.com/nhosoya/omniauth-apple/pull/62
