### ISSUE TITLE
undefined method verify for nil:NilClass in jwt.rb:62:in verify_rsa

### ISSUE THREAD

**Issue by PMajesty** [nhosoya/omniauth-apple#36]
I am getting this error: `undefined method verify for nil:NilClass in jwt.rb:62:in verify_rsa` on the callback. The `public_key` is `nil` in the method `verify_rsa` in the jwt gem.

My config is set up like this:

```
:apple,
ENV['APPLE_SIGN_IN_CLIENT_ID'], '',
{
  scope: 'email name',
  redirect_uri: ENV['APPLE_SIGN_IN_REDIRECT_URL'],
  pem: File.read(ENV['APPLE_SIGN_IN_PEM_PATH']),
  team_id: ENV['APPLE_SIGN_IN_TEAM_ID'],
  key_id: ENV['APPLE_SIGN_IN_KEY_ID'],
},
```

**Comment by PMajesty** [comment]
My bad, if you are having this error, you need to update JWT

**Comment by AnTienTL** [comment]
Hi @PMajesty . What version of jwt you update? i have same problem, but i update to newest of jwt, the error still here.

**Comment by PMajesty** [comment]
> Hi @PMajesty . What version of jwt you update? i have same problem, but i update to newest of jwt, the error still here.

I am sorry, but I no longer have access to that repository, I don't remember the version, but maybe you should try the one added as a dependancy in https://github.com/YuheiNakasaka/omniauth-apple/commit/57d6eeebe9ce49ba70de1fe12310fe7cb9cee334 ?
