### ISSUE TITLE
Doesn't receive code in mobile browser

### ISSUE THREAD

**Issue by vitalinfo** [nhosoya/omniauth-apple#57]
Everything works fine on desktop, but if I do Apple login from the mobile browser I don't receive `code` param in the callback.

**Comment by skotchpine** [comment]
@vitalinfo _**Help is cheaper with context.**_

Anyone able to help would probably want more detail. You could include:

- what you expect vs what is happening
- the platform and browser that don't do what you expect (as well as those that do)
- the versions of all relevant dependencies (a `Gemfile.lock` would do)
- the real code you're running (preferably without sensitive info)
- the config code you're using (especially without sensitive info)
- maybe screenshots of everything (if possible without sensitive info)

**Comment by nov** [comment]
do you still have problems in mobile browsers?
