### ISSUE TITLE
Authentication failure! invalid_credentials: OAuth2::Error, invalid_request: {"error":"invalid_request"}

### ISSUE THREAD

**Issue by flukedev8** [nhosoya/omniauth-apple#60]
Hi  I have no idea, Can you Help me Plz 👏🙏🙏

` INFO -- omniauth: (apple) Callback phase initiated.
 ERROR -- omniauth: (apple) Authentication failure! invalid_credentials: OAuth2::Error, invalid_request:
{"error":"invalid_request"}`

[
![image](https://user-images.githubusercontent.com/25680524/95324152-7c318180-08c9-11eb-8c99-1b46f461261a.png)
](url)

**Comment by zfahh** [comment]
i got this issue too

**Comment by flukedev8** [comment]
I'am so sorry , I found solution key_id not match on `.ENV` You should check Key_id again.
