### ISSUE TITLE
How to retrieve email and name?

### ISSUE THREAD

**Issue by fjaeger** [nhosoya/omniauth-apple#8]
After having received an access token, how would we get the user's email or name that we initially requested via the scopes?

I could not find any details about that part of the authentication from Apple...

**Comment by nhosoya** [comment]
@fjaeger 
Unfortunately there is no way to get email and name at the moment.
I'm looking forward to being updated and getting them available.

**Comment by merefield** [comment]
Why was this closed?  What was the resolution?  What's the dependency? Thanks!

**Comment by maszuDEV** [comment]
Still no solution for this issue. I think it should be reopened.

**Comment by willc0de4food** [comment]
So is the conclusion that we can't get the user's name from Apple?
