### ISSUE TITLE
Apple's /auth/revoke supported?

### ISSUE THREAD

**Issue by matthewkrom** [nhosoya/omniauth-apple#80]
Is Apple's /auth/revoke supported? Depending on the app's flow, this may be required for apps submitted by June 30, 2022. Reference: `https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens`

**Comment by nov** [comment]
this gem doesn't support token revocation.
use `apple_id` gem for that https://github.com/nov/apple_id/wiki/Client#revoke-tokens
