### ISSUE TITLE
Oauth2 version 2.0.0 breaks omniauth-apple

### ISSUE THREAD

**Issue by dli1022** [nhosoya/omniauth-apple#85]
Specifically this line in the Oauth2 2.0.0 release changelog breaks omniauth-apple gem:

"https://github.com/oauth-xx/oauth2/pull/312 - BREAKING: Set :basic_auth as default for :auth_scheme instead of :request_body. This was default behavior before 1.3.0. (@tetsuya, @wy193777)

Apple get token call needs the "client_id" and "client_secret" in the body, which will only be sent if Oauth2 "auth_scheme" type is ":request_body" 

Please provide a fix or advice how we can set the :auth_scheme to :request_body through omniquth options. 
Thanks

**Comment by thenathanjones** [comment]
@nhosoya how can we help get some progress on updating to support OAuth 2.0.0? Many of us using this are also using Facebook and Google strategies which work with the new version and it feels risky to not be able to update.

**Comment by smenor** [comment]
Just tagging on a « me-too » to this @nhosoya

**Comment by smenor** [comment]
Thank you !

**Comment by thenathanjones** [comment]
Indeed, thank you!
