### ISSUE TITLE
with JavaScript SDK provided by Apple

### ISSUE THREAD

**Issue by nhosoya** [nhosoya/omniauth-apple#9]
I think it is difficult to use this gem with the [JS SDK provided by Apple](https://developer.apple.com/documentation/signinwithapplejs) at this time.

In the first place, I need to investigate what difference about UX using and not using the Apple-provided JS SDK (e.g. whether Safari shows a native view).

**Comment by fjaeger** [comment]
I also tried this, but Omniauth seems to have an issue when it only handles the callback phase.

**Comment by fjaeger** [comment]
This should be solved by the latest changes, too

**Comment by maxencehenneron** [comment]
Any progress on this? If I understand correctly, we need to use the callback phase only? Would setting "provider_ignores_state" to true work? This would ignore the state param which is what is blocking us.

**Comment by skotchpine** [comment]
Why would you want to use Apple's JS SDK?

**Comment by nov** [comment]
I guess no issues anymore?
