### ISSUE TITLE
Remove version lock for rack-protection

### ISSUE THREAD

**Issue by thenathanjones** [nhosoya/omniauth-apple#93]
Hey folks,

https://github.com/nhosoya/omniauth-apple/blob/04793eae1428ad45dca0d194bfa4e24d3ca9c51d/omniauth-apple.gemspec#L41

According to the [referenced issue](https://github.com/omniauth/omniauth/pull/1090) this problem has now been resolved. Can this requirement please be removed now? We have already upgraded to the later version, but this lock is forcing a downgrade for us.

Thanks!
Nathan

**Comment by thenathanjones** [comment]
Heya @nov! Any idea when you'll be publishing this change to Rubygems? 🙏

**Comment by nov** [comment]
sorry for the delay.
I've released v1.2.1 with your changes.
thanks!

**Comment by thenathanjones** [comment]
No need to apologise @nov thank you!
